name: Package

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

concurrency:
  group: package
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install build dependencies
        run: pip install build pyinstaller
      - name: Install FFmpeg and MKVToolNix
        run: sudo apt-get update && sudo apt-get install -y ffmpeg mkvtoolnix
      - name: Build package
        run: python -m build
      - name: Build standalone bundle
        run: pyinstaller mkv-cleaner.spec --distpath bundle --onefile
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mkv-cleaner-dist
          path: dist/*
      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: mkv-cleaner-bundle
          path: bundle/*
