on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[build]

      - name: Build executable
        run: python build_exe.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MKVCleaner
          path: dist/MKVCleaner.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MKVCleaner.exe
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
